### PR TITLE
corrections/updates for building under Windows

### PR DESCRIPTION
**Pull request by TheTechsTech**
- added general linux/unix headers for Windows, will be needed to get other parts working
- examples execute/pass as expected using VS 2019

### CODE REVIEW

**Comment by XiaochenCui** [comment]
I don't have a Windows environment, but the pr looks reasonable.

**Comment by TheTechsTech** [comment]
> I don't have a Windows environment, but the pr looks reasonable.

I was in the process of creating GitHub Actions CI for testing and found that I mistakenly messed up CMakeLists.txt, by extra tokens getting `Parse error` now, has `libtask` at bottom needs to be removed.

Also the build process in there adding all `*.c` and `*.h`, you should update to exclude the two Windows files `ucontext.c` and `ucontext.h` or put conditionals inside them to not build if not Windows. 

I had to removed `set(CMAKE_C_COMPILER "gcc-9")` was causing Linux build fails initially, it could not find `gcc`. Everything builds without that.

**Comment by XiaochenCui** [comment]
@TheTechsTech No worries, it was just used for my content-switch research two years ago. I don't use it anymore.

**Comment by TheTechsTech** [comment]
I don't use this library directly, reworking parts into my https://github.com/symplely/c-coroutine library instead.

**Pull request merged**
